packages:
  - website

allowBuilds:
  esbuild: true
  spawn-sync: true
  workerd: true

minimumReleaseAgeExclude:
  - astro@7.2.0

overrides:
  firefox-profile>adm-zip: 0.6.0
  fx-runner>shell-quote: 1.10.0
  web-ext-run>multimatch: 8.0.0
  web-ext-run>tmp: 0.2.7
